### ISSUE TITLE
용어 선택: 보안취약성 vs 보안취약점

### ISSUE THREAD

**Issue by syleeeee** [NIPA-OpenUP/oss-governance-guide#79]
본문에 전반적으로 `보안취약성` 이라는 용어가 사용되고 있는데요, 평소에는 `보안취약점` 이라는 용어가 더 널리 사용되는 것 같습니다. 
[NIPA에서도 `보안취약점`](https://www.oss.kr/info_sec) 이라고 사용하고 있기도 합니다. 

두 용어가 가진 의미의 미묘한 차이에 대해서 정리한 [글](https://hakawati.co.kr/182)이 있는데요.

본문에서 사용하는 용어를 어느 한 쪽으로 통일할지, 의미에 따라 구분하여 사용할지 결정이 필요합니다.

**Comment by haksungjang** [comment]
@revfactory 

보안취약성  vs 보안취약점 용어에 대한 의견 부탁 드립니다. 

(참고)
오픈업 (백영석) : 
저희는 vernerability를 (보안)취약점으로 사용하고 있습니다. (예: 공개소프트웨어 보안취약점)
내부 문서에서도 보안취약성보다는 보안취약점을 많이 사용하고 있습니다.
취약성은 특정 부분 정도로만 사용하고 있습니다.
(ex 외부 공격자에 의한 네트워크 공격에 취약하다)

**Comment by revfactory** [comment]
백영석님 의견에 동의합니다

**Comment by haksungjang** [comment]
@revfactory 님, 의견 감사합니다. 
github pages 작업 시, '보안취약점'으로 용어 통일하겠습니다.
