### ISSUE TITLE
주요 오픈소스 관리도구 목록에..

### ISSUE THREAD

**Issue by minsuklee** [NIPA-OpenUP/oss-governance-guide#84]
현재 Olive .. SPDX.. ClearlyDefined 까지 있는데요.
국내의 solution 들
  저작권 위원회의 code-eye, 엘에스웨어의 foddguard, IotCube의 레브라도, Insignary의 clarity
블랙덕의 protex (요즘에도 있는지 모르지만)

등이 빠졌는데, 특별한 이유가 있는지요? 
그렇지 않다면 기왕이면 (좀 부족하더라도) 국내 solution들도 포함시키면 좋겠습니다.

**Comment by haksungjang** [comment]
학장님, 의견 감사합니다. 
말씀하신 국내 개발 도구(codeeye, labrador, clarity) 및 국내 업체들이 판매하고 있는 도구 (black duck, FOSSID) 등을 추가하겠습니다. 
단, LSware의 fossguard는 홈페이지에서도 관련 소개를 찾지 못하여 (서비스를 중단한 걸지도) 제외하겠습니다.
