### ISSUE TITLE
ToC level 조절

### ISSUE THREAD

**Issue by haksungjang** [NIPA-OpenUP/oss-governance-guide#85]
ToC를 확인해보니, 현재 다음과 같은데요, 

0. 요약
1. 오픈소스 사용하기
2. 오픈소스 사용 가이드 - 기업편
3. 오픈소스 사용 가이드 - 개발자편
4. 오픈소스 기여하기
5. 오픈소스 기여하기 - 기업편
6. 오픈소스 기여하기 - 개발자편
7. 오픈소스 공개하기
8. 오픈소스 공개 가이드 - 기업편
9. 오픈소스 공개 가이드 - 개발자편
10. OSPO

아래와 같이 변경해야 할 것 같습니다. 

0. 요약
1. 오픈소스 사용하기
   - 오픈소스 사용 가이드 - 기업편
   - 오픈소스 사용 가이드 - 개발자편
2. 오픈소스 기여하기
   - 오픈소스 기여 가이드 - 기업편
   - 오픈소스 사용 가이드 - 개발자편
3. 오픈소스 공개하기
   - 오픈소스 공개 가이드 - 기업편
   - 오픈소스 공개 가이드 - 개발자편
4. OSPO

이를 위해 ToC 레벨 조정하겠습니다. 혹시, 다른 의견 있으신 분들은 알려주세요! ;)

**Comment by minsuklee** [comment]
아울러 문서가 하나의 md 파일로 되어 있는데, 위 toc 번호에 따라 4-5조각으로 나누면 좋을 듯 합니다.

**Comment by haksungjang** [comment]
@minsuklee 학장님, 의견 주신 4-5조각으로 나누는 사항은 별도 issue를 생성하여 대응하겠습니다.
