### ISSUE TITLE
git, github 사용 부분에

### ISSUE THREAD

**Issue by minsuklee** [NIPA-OpenUP/oss-governance-guide#87]
인터넷에 있는 유무료 강좌의 링크, 무료 PDF 파일들을 추가하면 어떨까 합니다.

**Comment by haksungjang** [comment]
@minsuklee 학장님! 의견 감사합니다.
혹시, 추천하실만한 강좌, 파일들이 있다면 공유 부탁 드려도 될까요?

**Comment by minsuklee** [comment]
https://github.com/innovationacademy-kr/hitchhikers_guide/blob/main/git.md 에 보면 우리 학생들이 추천하는 자료가 있고,
-- 
동영상은 좀 https://www.inflearn.com/courses?s=git%20github 에 보시면 후보들이 있습니다.
생활코딩 (이고잉) 동영상이 무료이고 쉬워서 좋을 듯 합니다.

**Comment by haksungjang** [comment]
감사합니다, 학장님!
알려주신 추천 자료를 추가하겠습니다. 
추천 자료 내에 생활코딩 (egoing) 동영상이 포함되어 있어서, 학생 추천 자료만을 가이드에 추가하겠습니다.
